apiVersion: v1
kind: Service
metadata:
  name: assets-webapi-service
spec:
  selector:
    app: assets-webapi
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: assets-webapi-port-http
    # - protocol: TCP
    #   port: 443
    #   targetPort: 443
    #   name: assets-webapi-port-https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets-webapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assets-webapi
  template:
    metadata:
      labels:
        app: assets-webapi
    spec:
      containers:
        - name: assets-webapi
          image: radiksalakhov/assets-webapi:{PROD_VERSION}
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:80
              #value: http://0.0.0.0:80;https://0.0.0.0:443            
            - name: ConnectionStrings__EventBus
              value: 'rabbitmq-service.default'
            - name: AssetsOptions__BinanceWorkerApiGrpc
              value: http://binance-worker-service.default:90