# apiVersion: v1
# kind: Service
# metadata:
#   name: binance-worker-service
# spec:
#   selector:
#     app: binance-worker
#   type: ClusterIP  
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: binance-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binance-worker
  template:
    metadata:
      labels:
        app: binance-worker
    spec:
      containers:
        - name: binance-worker
          image: radiksalakhov/ts-binance-worker:prod
          imagePullPolicy: Always
          env:
            - name: DOTNET_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__EventBus
              value: 'rabbitmq-service.default'
            - name: BinanceOptions__BinanceApiKey
              valueFrom:
                configMapKeyRef:
                  name: secret-config-map
                  key: BinanceOptions__BinanceApiKey              
            - name: BinanceOptions__BinanceApiSecret
              valueFrom:
                configMapKeyRef:
                  name: secret-config-map
                  key: BinanceOptions__BinanceApiSecret
            