apiVersion: v1
kind: Service
metadata:  
  name: binance-worker-service
spec:
  selector:
    app: binance-worker
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 90
      targetPort: 90
      name: binance-worker-port-grpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: binance-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binance-worker
  template:
    metadata:
      labels:
        app: binance-worker
    spec:
      containers:
        - name: binance-worker
          image: radiksalakhov/ts-binance-worker:{PROD_VERSION}
          imagePullPolicy: Always
          env:
            - name: DOTNET_ENVIRONMENT
              value: Development
            - name: Kestrel__Endpoints__GRPC__Url
              value: http://0.0.0.0:90
            - name: Kestrel__Endpoints__GRPC__Protocols
              value: Http2
            - name: ConnectionStrings__EventBus
              value: 'rabbitmq-service.default'
            - name: BinanceOptions__BinanceApiKey
              valueFrom:
                configMapKeyRef:
                  name: secret-config-map
                  key: BinanceOptions__BinanceApiKey              
            - name: BinanceOptions__BinanceApiSecret
              valueFrom:
                configMapKeyRef:
                  name: secret-config-map
                  key: BinanceOptions__BinanceApiSecret
            