apiVersion: v1
kind: Service
metadata:
  name: gateway-service  
spec:
  selector:
    app: gateway
  type: LoadBalancer
  loadBalancerIP: 195.20.246.216
  ports:        
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: gateway-port
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: gateway-admin-port    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: radiksalakhov/ts-gateway:{PROD_VERSION}
          imagePullPolicy: Always