apiVersion: v1
kind: Service
metadata:
  name: ticker-signalrhub-service
spec:
  selector:
    app: ticker-signalrhub
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: ticker-signalrhub-port-http
    # - protocol: TCP
    #   port: 443
    #   targetPort: 443
    #   name: blazorapp-port-https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticker-signalrhub-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticker-signalrhub
  template:
    metadata:
      labels:
        app: ticker-signalrhub
    spec:
      containers:
        - name: ticker-signalrhub
          image: radiksalakhov/ts-ticker-signalrhub:prod
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:80
              #value: http://0.0.0.0:80;https://0.0.0.0:443
            - name: ConnectionStrings__EventBus
              value: 'rabbitmq-service.default'