// <auto-generated />
using Assets.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assets.Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230710145353_iteration-000")]
    partial class iteration000
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assets.Persistence.DBModels.AssetDB", b =>
                {
                    b.Property<string>("AssetType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BaseAsset")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("LotStepSize")
                        .HasColumnType("decimal(38,19)");

                    b.HasKey("AssetType", "BaseAsset");

                    b.ToTable("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
