version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine

  binance-backgroundtasks:
    image: ${REGISTRY:-radiksalakhov}tradingsuite-binancebackgroundtasks
    build:
      context: .
      dockerfile: Services/Binance/Binance.BackgroundTasks/Dockerfile
    depends_on:
      - rabbitmq

  taapi-backgroundtasks:
    image: ${REGISTRY:-radiksalakhov}tradingsuite-taapibackgroundtasks
    build:
      context: .
      dockerfile: Services/TaApi/TaApi.BackgroundTasks/Dockerfile
    depends_on:
      - rabbitmq

  ticker-signalrhub:
    image: ${REGISTRY:-radiksalakhov}tradingsuite-tickersignalrhub
    build:
      context: .
      dockerfile: Services/Ticker/ticker.SignalrHub/Dockerfile
    depends_on:
      - rabbitmq

  blazorapp:
    image: ${REGISTRY:-radiksalakhov}tradingsuite-blazorapp
    build:
      context: .
      dockerfile: WebApps/BlazorApp/Server/Dockerfile    

