version: '3.4'

services:
  gateway:
    image: radiksalakhov/ts-gateway:${PROD_VERSION}
    build:
      context: .
      dockerfile: ApiGateways/EnvoyProd/Dockerfile
    volumes:
      - ./ApiGateways/EnvoyProd/envoy.yaml:/etc/envoy/envoy.yaml

  assets-api:
    image: radiksalakhov/assets-api:${PROD_VERSION}
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      
  binance-worker:
    image: radiksalakhov/ts-binance-worker:${PROD_VERSION}
    environment:
      - DOTNET_ENVIRONMENT=Development    

  taapi-worker:
    image: radiksalakhov/ts-taapi-worker:${PROD_VERSION}
    environment:
      - DOTNET_ENVIRONMENT=Development    

  ticker-signalrhub:
    image: radiksalakhov/ts-ticker-signalrhub:${PROD_VERSION}    

  blazorapp:
    image: radiksalakhov/ts-blazorapp:${PROD_VERSION}
    environment:
      - ASPNETCORE_ENVIRONMENT=Development     