version: '3.4'

services:
  gateway:
    image: radiksalakhov/ts-gateway:latest
    build:
      context: .
      dockerfile: ApiGateways/EnvoyDev/Dockerfile
    volumes:
      - ./ApiGateways/EnvoyDev/envoy.yaml:/etc/envoy/envoy.yaml

  assets-webapi:
    image: radiksalakhov/assets-webapi:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      
  binance-worker:
    image: radiksalakhov/ts-binance-worker:latest
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  taapi-worker:
    image: radiksalakhov/ts-taapi-worker:latest
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  ticker-signalrhub:
    image: radiksalakhov/ts-ticker-signalrhub:latest    

  blazorapp:
    image: radiksalakhov/ts-blazorapp:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development     