version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine

  binance-backgroundtasks:
    image: ${REGISTRY:-radiksalakhov}tradingsuite-binancebackgroundtasks
    build:
      context: .
      dockerfile: Services/Binance/Binance.BackgroundTasks/Dockerfile
    depends_on:
      - rabbitmq

  priceticker-signalrhub:
    image: ${REGISTRY:-radiksalakhov}tradingsuite-pricetickersignalrhub
    build:
      context: .
      dockerfile: Services/PriceTicker/priceticker.SignalrHub/Dockerfile
    depends_on:
      - rabbitmq

  blazorapp:
    image: ${REGISTRY:-radiksalakhov}tradingsuite-blazorapp
    build:
      context: .
      dockerfile: WebApps/BlazorApp/Server/Dockerfile    

