version: '3.4'

services:
  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"      

  binance-backgroundtasks:
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  priceticker-signalrhub:
    ports:
      - "6090:80"      

  blazorapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80;https://0.0.0.0:443
      - SignalrHubUrl=http://localhost:6090/hub
    ports:
      - "6080:80"
      - "6081:443"

