version: '3.4'

services:
  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"      

  binance-worker:
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  taapi-worker:
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  ticker-signalrhub:
   environment:
     - ASPNETCORE_URLS=http://0.0.0.0:80
   ports:
     - "6090:80"

  blazorapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      #- ASPNETCORE_URLS=http://0.0.0.0:80;https://0.0.0.0:443
    ports:
      - "6080:80"
      - "6081:443"