version: '3.4'

services:
  gateway:
    ports:
      - "80:80"
      - "8080:8080"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"    

  assets-api:
    build:
      context: .
      dockerfile: Services/Assets/Assets.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - AssetsAPIOptions__BinanceWorkerApiGrpc=http://binance-worker:90
    ports:
      - "6004:80"
    depends_on:
      - rabbitmq  

  binance-worker:
    build:
      context: .
      dockerfile: Services/Binance/Binance.Worker/Dockerfile
    environment:
      - Kestrel__Endpoints__GRPC__Url=http://0.0.0.0:90
      - Kestrel__Endpoints__GRPC__Protocols=Http2    
    depends_on:
      - rabbitmq

  taapi-worker:    
    build:
      context: .
      dockerfile: Services/TaApi/TaApi.Worker/Dockerfile
    depends_on:
      - rabbitmq

  ticker-signalrhub:   
    build:
      context: .
      dockerfile: Services/Ticker/ticker.SignalrHub/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "6002:80"
    depends_on:
      - rabbitmq

  blazorapp:    
    build:
      context: .
      dockerfile: WebApps/BlazorApp/Server/Dockerfile    
    environment:      
      - ASPNETCORE_URLS=http://0.0.0.0:80
      #- ASPNETCORE_URLS=http://0.0.0.0:80;https://0.0.0.0:443
    ports:
      - "6000:80"
      - "6001:443"
    depends_on:
      - rabbitmq