version: '3.4'

services:
  gateway:
    ports:
      - "80:8000"
      - "8080:8080"
  
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - MSSQL_PID=Developer
      - SA_PASSWORD=DevPassword1!
      - ACCEPT_EULA=Y
    volumes:
      - D:\Docker\trading-suite\dev\sql-server\data:/var/opt/mssql/data
      - D:\Docker\trading-suite\dev\sql-server\log:/var/opt/mssql/log
      - D:\Docker\trading-suite\dev\sql-server\secrets:/var/opt/mssql/secrets

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"    

  assets-webapi:
    build:
      context: .
      dockerfile: Services/Assets/Assets.WebApi/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - AssetsOptions__BinanceWorkerApiGrpc=http://binance-worker:90
    ports:
      - "6004:80"
    depends_on:
      - rabbitmq  

  binance-worker:
    build:
      context: .
      dockerfile: Services/Binance/Binance.Worker/Dockerfile
    environment:
      - Kestrel__Endpoints__GRPC__Url=http://0.0.0.0:90
      - Kestrel__Endpoints__GRPC__Protocols=Http2    
    depends_on:
      - rabbitmq

  taapi-worker:    
    build:
      context: .
      dockerfile: Services/TaApi/TaApi.Worker/Dockerfile
    depends_on:
      - rabbitmq

  ticker-signalrhub:   
    build:
      context: .
      dockerfile: Services/Ticker/ticker.SignalrHub/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "6002:80"
    depends_on:
      - rabbitmq

  blazorapp:    
    build:
      context: .
      dockerfile: WebApps/BlazorApp/Server/Dockerfile    
    environment:      
      - ASPNETCORE_URLS=http://0.0.0.0:80
      #- ASPNETCORE_URLS=http://0.0.0.0:80;https://0.0.0.0:443
    ports:
      - "6000:80"
      - "6001:443"
    depends_on:
      - rabbitmq