version: '3.4'

services:
  ts-rabbitmq:
    image: rabbitmq:3-management-alpine

  ts-binance-worker:
    image: radiksalakhov/ts-binance-worker:latest
    build:
      context: .
      dockerfile: Services/Binance/Binance.BackgroundTasks/Dockerfile
    depends_on:
      - ts-rabbitmq

  ts-taapi-worker:
    image: radiksalakhov/ts-taapi-worker:latest
    build:
      context: .
      dockerfile: Services/TaApi/TaApi.BackgroundTasks/Dockerfile
    depends_on:
      - ts-rabbitmq

  #ts-ticker-signalrhub:
  #  image: radiksalakhov/ts-ticker-signalrhub:latest
  #  build:
  #    context: .
  #    dockerfile: Services/Ticker/ticker.SignalrHub/Dockerfile
  #  depends_on:
  #    - ts-rabbitmq

  ts-blazorapp:
    image: radiksalakhov/ts-blazorapp:latest
    build:
      context: .
      dockerfile: WebApps/BlazorApp/Server/Dockerfile    
    depends_on:
      - ts-rabbitmq

