version: '3.4'

services:
  gateway:
    image: radiksalakhov/ts-gateway:prod
    build:
      context: .
      dockerfile: ApiGateways/EnvoyProd/Dockerfile

  binance-worker:
    image: radiksalakhov/ts-binance-worker:prod
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  taapi-worker:
    image: radiksalakhov/ts-taapi-worker:prod
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  ticker-signalrhub:
    image: radiksalakhov/ts-ticker-signalrhub:prod

  blazorapp:
    image: radiksalakhov/ts-blazorapp:prod
    environment:
      - ASPNETCORE_ENVIRONMENT=Development     