version: '3.4'

services:
  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"      

  binance-backgroundtasks:
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  taapi-backgroundtasks:
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  ticker-signalrhub:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:6090
    ports:
      - "6090:6090"

  blazorapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80      
    ports:
      - "6080:80"
      - "6081:443"

