version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine

  binance-backgroundtasks:
    image: tradingsuitecr.azurecr.io/binancebackgroundtasks
    build:
      context: .
      dockerfile: Services/Binance/Binance.BackgroundTasks/Dockerfile
    depends_on:
      - rabbitmq

  taapi-backgroundtasks:
    image: tradingsuitecr.azurecr.io/taapibackgroundtasks
    build:
      context: .
      dockerfile: Services/TaApi/TaApi.BackgroundTasks/Dockerfile
    depends_on:
      - rabbitmq

  ticker-signalrhub:
    image: tradingsuitecr.azurecr.io/tickersignalrhub
    build:
      context: .
      dockerfile: Services/Ticker/ticker.SignalrHub/Dockerfile
    depends_on:
      - rabbitmq

  blazorapp:
    image: tradingsuitecr.azurecr.io/tradingsuite-blazorapp
    build:
      context: .
      dockerfile: WebApps/BlazorApp/Server/Dockerfile    

